/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ChallangesFeedbackImport } from './routes/challanges.feedback'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ChallangesFeedbackRoute = ChallangesFeedbackImport.update({
  id: '/challanges/feedback',
  path: '/challanges/feedback',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/challanges/feedback': {
      id: '/challanges/feedback'
      path: '/challanges/feedback'
      fullPath: '/challanges/feedback'
      preLoaderRoute: typeof ChallangesFeedbackImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/challanges/feedback': typeof ChallangesFeedbackRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/challanges/feedback': typeof ChallangesFeedbackRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/challanges/feedback': typeof ChallangesFeedbackRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/challanges/feedback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/challanges/feedback'
  id: '__root__' | '/' | '/challanges/feedback'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChallangesFeedbackRoute: typeof ChallangesFeedbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChallangesFeedbackRoute: ChallangesFeedbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/challanges/feedback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/challanges/feedback": {
      "filePath": "challanges.feedback.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
